=== api-evangelist/amazon-device-farm/json-schema/amazon-device-farm-job-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-device-farm/refs/heads/main/json-schema/amazon-device-farm-job-schema.json",
  "title": "Job",
  "description": "Represents a device.",
  "type": "object",
  "properties": {
    "arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AmazonResourceName"
        },
        {
          "description": "The job's ARN."
        }
      ]
    },
    "name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Name"
        },
        {
          "description": "The job's name."
        }
      ]
    },
    "type": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TestType"
        },
        {
          "description": "<p>The job's type.</p> <p>Allowed values include the following:</p> <ul> <li> <p>BUILTIN_FUZZ</p> </li> <li> <p>BUILTIN_EXPLORER. For Android, an app explorer that traverses an Android app, interacting with it and capturing screenshots at the same time.</p> </li> <li> <p>APPIUM_JAVA_JUNIT</p> </li> <li> <p>APPIUM_JAVA_TESTNG</p> </li> <li> <p>APPIUM_PYTHON</p> </li> <li> <p>APPIUM_NODE</p> </li> <li> <p>APPIUM_RUBY</p> </li> <li> <p>APPIUM_WEB_JAVA_JUNIT</p> </li> <li> <p>APPIUM_WEB_JAVA_TESTNG</p> </li> <li> <p>APPIUM_WEB_PYTHON</p> </li> <li> <p>APPIUM_WEB_NODE</p> </li> <li> <p>APPIUM_WEB_RUBY</p> </li> <li> <p>CALABASH</p> </li> <li> <p>INSTRUMENTATION</p> </li> <li> <p>UIAUTOMATION</p> </li> <li> <p>UIAUTOMATOR</p> </li> <li> <p>XCTEST</p> </li> <li> <p>XCTEST_UI</p> </li> </ul>"
        }
      ]
    },
    "created": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DateTime"
        },
        {
          "description": "When the job was created."
        }
      ]
    },
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ExecutionStatus"
        },
        {
          "description": "<p>The job's status.</p> <p>Allowed values include:</p> <ul> <li> <p>PENDING</p> </li> <li> <p>PENDING_CONCURRENCY</p> </li> <li> <p>PENDING_DEVICE</p> </li> <li> <p>PROCESSING</p> </li> <li> <p>SCHEDULING</p> </li> <li> <p>PREPARING</p> </li> <li> <p>RUNNING</p> </li> <li> <p>COMPLETED</p> </li> <li> <p>STOPPING</p> </li> </ul>"
        }
      ]
    },
    "result": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ExecutionResult"
        },
        {
          "description": "<p>The job's result.</p> <p>Allowed values include:</p> <ul> <li> <p>PENDING</p> </li> <li> <p>PASSED</p> </li> <li> <p>WARNED</p> </li> <li> <p>FAILED</p> </li> <li> <p>SKIPPED</p> </li> <li> <p>ERRORED</p> </li> <li> <p>STOPPED</p> </li> </ul>"
        }
      ]
    },
    "started": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DateTime"
        },
        {
          "description": "The job's start time."
        }
      ]
    },
    "stopped": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DateTime"
        },
        {
          "description": "The job's stop time."
        }
      ]
    },
    "counters": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Counters"
        },
        {
          "description": "The job's result counters."
        }
      ]
    },
    "message": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Message"
        },
        {
          "description": "A message about the job's result."
        }
      ]
    },
    "device": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Device"
        },
        {
          "description": "The device (phone or tablet)."
        }
      ]
    },
    "instanceArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AmazonResourceName"
        },
        {
          "description": "The ARN of the instance."
        }
      ]
    },
    "deviceMinutes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DeviceMinutes"
        },
        {
          "description": "Represents the total (metered or unmetered) minutes used by the job."
        }
      ]
    },
    "videoEndpoint": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The endpoint for streaming device video."
        }
      ]
    },
    "videoCapture": {
      "allOf": [
        {
          "$ref": "#/components/schemas/VideoCapture"
        },
        {
          "description": "This value is set to true if video capture is enabled. Otherwise, it is set to false."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-device-farm/examples/amazon-device-farm-job-example.json
{
  "arn": "arn:aws:devicefarm:us-west-2:123456789012:project:abc123",
  "name": "Example name",
  "type": "BUILTIN_FUZZ",
  "created": "example-created",
  "status": "COMPLETED",
  "result": "PASSED",
  "started": "example-started",
  "stopped": "example-stopped",
  "counters": "example-counters",
  "message": "An example message",
  "device": "example-device",
  "instanceArn": "arn:aws:devicefarm:us-west-2:123456789012:project:abc123",
  "deviceMinutes": "example-deviceMinutes",
  "videoEndpoint": "example-videoEndpoint",
  "videoCapture": "example-videoCapture"
}
