=== api-evangelist/amazon-device-farm/json-schema/amazon-device-farm-upload-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-device-farm/refs/heads/main/json-schema/amazon-device-farm-upload-schema.json",
  "title": "Upload",
  "description": "An app or a set of one or more tests to upload or that have been uploaded.",
  "type": "object",
  "properties": {
    "arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AmazonResourceName"
        },
        {
          "description": "The upload's ARN."
        }
      ]
    },
    "name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Name"
        },
        {
          "description": "The upload's file name."
        }
      ]
    },
    "created": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DateTime"
        },
        {
          "description": "When the upload was created."
        }
      ]
    },
    "type": {
      "allOf": [
        {
          "$ref": "#/components/schemas/UploadType"
        },
        {
          "description": "<p>The upload's type.</p> <p>Must be one of the following values:</p> <ul> <li> <p>ANDROID_APP</p> </li> <li> <p>IOS_APP</p> </li> <li> <p>WEB_APP</p> </li> <li> <p>EXTERNAL_DATA</p> </li> <li> <p>APPIUM_JAVA_JUNIT_TEST_PACKAGE</p> </li> <li> <p>APPIUM_JAVA_TESTNG_TEST_PACKAGE</p> </li> <li> <p>APPIUM_PYTHON_TEST_PACKAGE</p> </li> <li> <p>APPIUM_NODE_TEST_PACKAGE</p> </li> <li> <p>APPIUM_RUBY_TEST_PACKAGE</p> </li> <li> <p>APPIUM_WEB_JAVA_JUNIT_TEST_PACKAGE</p> </li> <li> <p>APPIUM_WEB_JAVA_TESTNG_TEST_PACKAGE</p> </li> <li> <p>APPIUM_WEB_PYTHON_TEST_PACKAGE</p> </li> <li> <p>APPIUM_WEB_NODE_TEST_PACKAGE</p> </li> <li> <p>APPIUM_WEB_RUBY_TEST_PACKAGE</p> </li> <li> <p>CALABASH_TEST_PACKAGE</p> </li> <li> <p>INSTRUMENTATION_TEST_PACKAGE</p> </li> <li> <p>UIAUTOMATION_TEST_PACKAGE</p> </li> <li> <p>UIAUTOMATOR_TEST_PACKAGE</p> </li> <li> <p>XCTEST_TEST_PACKAGE</p> </li> <li> <p>XCTEST_UI_TEST_PACKAGE</p> </li> <li> <p>APPIUM_JAVA_JUNIT_TEST_SPEC</p> </li> <li> <p>APPIUM_JAVA_TESTNG_TEST_SPEC</p> </li> <li> <p>APPIUM_PYTHON_TEST_SPEC</p> </li> <li> <p>APPIUM_NODE_TEST_SPEC</p> </li> <li> <p>APPIUM_RUBY_TEST_SPEC</p> </li> <li> <p>APPIUM_WEB_JAVA_JUNIT_TEST_SPEC</p> </li> <li> <p>APPIUM_WEB_JAVA_TESTNG_TEST_SPEC</p> </li> <li> <p>APPIUM_WEB_PYTHON_TEST_SPEC</p> </li> <li> <p>APPIUM_WEB_NODE_TEST_SPEC</p> </li> <li> <p>APPIUM_WEB_RUBY_TEST_SPEC</p> </li> <li> <p>INSTRUMENTATION_TEST_SPEC</p> </li> <li> <p>XCTEST_UI_TEST_SPEC</p> </li> </ul>"
        }
      ]
    },
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/UploadStatus"
        },
        {
          "description": "<p>The upload's status.</p> <p>Must be one of the following values:</p> <ul> <li> <p>FAILED</p> </li> <li> <p>INITIALIZED</p> </li> <li> <p>PROCESSING</p> </li> <li> <p>SUCCEEDED</p> </li> </ul>"
        }
      ]
    },
    "url": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SensitiveURL"
        },
        {
          "description": "The presigned Amazon S3 URL that was used to store a file using a PUT request."
        }
      ]
    },
    "metadata": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Metadata"
        },
        {
          "description": "The upload's metadata. For example, for Android, this contains information that is parsed from the manifest and is displayed in the AWS Device Farm console after the associated app is uploaded."
        }
      ]
    },
    "contentType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ContentType"
        },
        {
          "description": "The upload's content type (for example, <code>application/octet-stream</code>)."
        }
      ]
    },
    "message": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Message"
        },
        {
          "description": "A message about the upload's result."
        }
      ]
    },
    "category": {
      "allOf": [
        {
          "$ref": "#/components/schemas/UploadCategory"
        },
        {
          "description": "<p>The upload's category. Allowed values include:</p> <ul> <li> <p>CURATED: An upload managed by AWS Device Farm.</p> </li> <li> <p>PRIVATE: An upload managed by the AWS Device Farm customer.</p> </li> </ul>"
        }
      ]
    }
  }
}

=== api-evangelist/amazon-device-farm/examples/amazon-device-farm-upload-example.json
{
  "arn": "arn:aws:devicefarm:us-west-2:123456789012:project:abc123",
  "name": "Example name",
  "created": "example-created",
  "type": "BUILTIN_FUZZ",
  "status": "COMPLETED",
  "url": "https://example.com/resource",
  "metadata": "example-metadata",
  "contentType": "BUILTIN_FUZZ",
  "message": "An example message",
  "category": "example-category"
}
