=== api-evangelist/amazon-device-farm/json-schema/amazon-device-farm-suite-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-device-farm/refs/heads/main/json-schema/amazon-device-farm-suite-schema.json",
  "title": "Suite",
  "description": "Represents a collection of one or more tests.",
  "type": "object",
  "properties": {
    "arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AmazonResourceName"
        },
        {
          "description": "The suite's ARN."
        }
      ]
    },
    "name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Name"
        },
        {
          "description": "The suite's name."
        }
      ]
    },
    "type": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TestType"
        },
        {
          "description": "<p>The suite's type.</p> <p>Must be one of the following values:</p> <ul> <li> <p>BUILTIN_FUZZ</p> </li> <li> <p>BUILTIN_EXPLORER </p> <note> <p>Only available for Android; an app explorer that traverses an Android app, interacting with it and capturing screenshots at the same time.</p> </note> </li> <li> <p>APPIUM_JAVA_JUNIT</p> </li> <li> <p>APPIUM_JAVA_TESTNG</p> </li> <li> <p>APPIUM_PYTHON</p> </li> <li> <p>APPIUM_NODE</p> </li> <li> <p>APPIUM_RUBY</p> </li> <li> <p>APPIUM_WEB_JAVA_JUNIT</p> </li> <li> <p>APPIUM_WEB_JAVA_TESTNG</p> </li> <li> <p>APPIUM_WEB_PYTHON</p> </li> <li> <p>APPIUM_WEB_NODE</p> </li> <li> <p>APPIUM_WEB_RUBY</p> </li> <li> <p>CALABASH</p> </li> <li> <p>INSTRUMENTATION</p> </li> <li> <p>UIAUTOMATION</p> </li> <li> <p>UIAUTOMATOR</p> </li> <li> <p>XCTEST</p> </li> <li> <p>XCTEST_UI</p> </li> </ul>"
        }
      ]
    },
    "created": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DateTime"
        },
        {
          "description": "When the suite was created."
        }
      ]
    },
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ExecutionStatus"
        },
        {
          "description": "<p>The suite's status.</p> <p>Allowed values include:</p> <ul> <li> <p>PENDING</p> </li> <li> <p>PENDING_CONCURRENCY</p> </li> <li> <p>PENDING_DEVICE</p> </li> <li> <p>PROCESSING</p> </li> <li> <p>SCHEDULING</p> </li> <li> <p>PREPARING</p> </li> <li> <p>RUNNING</p> </li> <li> <p>COMPLETED</p> </li> <li> <p>STOPPING</p> </li> </ul>"
        }
      ]
    },
    "result": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ExecutionResult"
        },
        {
          "description": "<p>The suite's result.</p> <p>Allowed values include:</p> <ul> <li> <p>PENDING</p> </li> <li> <p>PASSED</p> </li> <li> <p>WARNED</p> </li> <li> <p>FAILED</p> </li> <li> <p>SKIPPED</p> </li> <li> <p>ERRORED</p> </li> <li> <p>STOPPED</p> </li> </ul>"
        }
      ]
    },
    "started": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DateTime"
        },
        {
          "description": "The suite's start time."
        }
      ]
    },
    "stopped": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DateTime"
        },
        {
          "description": "The suite's stop time."
        }
      ]
    },
    "counters": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Counters"
        },
        {
          "description": "The suite's result counters."
        }
      ]
    },
    "message": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Message"
        },
        {
          "description": "A message about the suite's result."
        }
      ]
    },
    "deviceMinutes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DeviceMinutes"
        },
        {
          "description": "Represents the total (metered or unmetered) minutes used by the test suite."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-device-farm/examples/amazon-device-farm-suite-example.json
{
  "arn": "arn:aws:devicefarm:us-west-2:123456789012:project:abc123",
  "name": "Example name",
  "type": "BUILTIN_FUZZ",
  "created": "example-created",
  "status": "COMPLETED",
  "result": "PASSED",
  "started": "example-started",
  "stopped": "example-stopped",
  "counters": "example-counters",
  "message": "An example message",
  "deviceMinutes": "example-deviceMinutes"
}
