=== api-evangelist/amazon-device-farm/json-schema/amazon-device-farm-remote-access-session-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-device-farm/refs/heads/main/json-schema/amazon-device-farm-remote-access-session-schema.json",
  "title": "RemoteAccessSession",
  "description": "Represents information about the remote access session.",
  "type": "object",
  "properties": {
    "arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AmazonResourceName"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the remote access session."
        }
      ]
    },
    "name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Name"
        },
        {
          "description": "The name of the remote access session."
        }
      ]
    },
    "created": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DateTime"
        },
        {
          "description": "The date and time the remote access session was created."
        }
      ]
    },
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ExecutionStatus"
        },
        {
          "description": "<p>The status of the remote access session. Can be any of the following:</p> <ul> <li> <p>PENDING.</p> </li> <li> <p>PENDING_CONCURRENCY.</p> </li> <li> <p>PENDING_DEVICE.</p> </li> <li> <p>PROCESSING.</p> </li> <li> <p>SCHEDULING.</p> </li> <li> <p>PREPARING.</p> </li> <li> <p>RUNNING.</p> </li> <li> <p>COMPLETED.</p> </li> <li> <p>STOPPING.</p> </li> </ul>"
        }
      ]
    },
    "result": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ExecutionResult"
        },
        {
          "description": "<p>The result of the remote access session. Can be any of the following:</p> <ul> <li> <p>PENDING.</p> </li> <li> <p>PASSED.</p> </li> <li> <p>WARNED.</p> </li> <li> <p>FAILED.</p> </li> <li> <p>SKIPPED.</p> </li> <li> <p>ERRORED.</p> </li> <li> <p>STOPPED.</p> </li> </ul>"
        }
      ]
    },
    "message": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Message"
        },
        {
          "description": "A message about the remote access session."
        }
      ]
    },
    "started": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DateTime"
        },
        {
          "description": "The date and time the remote access session was started."
        }
      ]
    },
    "stopped": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DateTime"
        },
        {
          "description": "The date and time the remote access session was stopped."
        }
      ]
    },
    "device": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Device"
        },
        {
          "description": "The device (phone or tablet) used in the remote access session."
        }
      ]
    },
    "instanceArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AmazonResourceName"
        },
        {
          "description": "The ARN of the instance."
        }
      ]
    },
    "remoteDebugEnabled": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "<p>This flag is set to <code>true</code> if remote debugging is enabled for the remote access session.</p> <p>Remote debugging is <a href=\"https://docs.aws.amazon.com/devicefarm/latest/developerguide/history.html\">no longer supported</a>.</p>"
        }
      ]
    },
    "remoteRecordEnabled": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "This flag is set to <code>true</code> if remote recording is enabled for the remote access session."
        }
      ]
    },
    "remoteRecordAppArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AmazonResourceName"
        },
        {
          "description": "The ARN for the app to be recorded in the remote access session."
        }
      ]
    },
    "hostAddress": {
      "allOf": [
        {
          "$ref": "#/components/schemas/HostAddress"
        },
        {
          "description": "<p>IP address of the EC2 host where you need to connect to remotely debug devices. Only returned if remote debugging is enabled for the remote access session.</p> <p>Remote debugging is <a href=\"https://docs.aws.amazon.com/devicefarm/latest/developerguide/history.html\">no longer supported</a>.</p>"
        }
      ]
    },
    "clientId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ClientId"
        },
        {
          "description": "<p>Unique identifier of your client for the remote access session. Only returned if remote debugging is enabled for the remote access session.</p> <p>Remote debugging is <a href=\"https://docs.aws.amazon.com/devicefarm/latest/developerguide/history.html\">no longer supported</a>.</p>"
        }
      ]
    },
    "billingMethod": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BillingMethod"
        },
        {
          "description": "The billing method of the remote access session. Possible values include <code>METERED</code> or <code>UNMETERED</code>. For more information about metered devices, see <a href=\"https://docs.aws.amazon.com/devicefarm/latest/developerguide/welcome.html#welcome-terminology\">AWS Device Farm terminology</a>."
        }
      ]
    },
    "deviceMinutes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DeviceMinutes"
        },
        {
          "description": "The number of minutes a device is used in a remote access session (including setup and teardown minutes)."
        }
      ]
    },
    "endpoint": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The endpoint for the remote access sesssion."
        }
      ]
    },
    "deviceUdid": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "<p>Unique device identifier for the remote device. Only returned if remote debugging is enabled for the remote access session.</p> <p>Remote debugging is <a href=\"https://docs.aws.amazon.com/devicefarm/latest/developerguide/history.html\">no longer supported</a>.</p>"
        }
      ]
    },
    "interactionMode": {
      "allOf": [
        {
          "$ref": "#/components/schemas/InteractionMode"
        },
        {
          "description": "<p>The interaction mode of the remote access session. Valid values are:</p> <ul> <li> <p>INTERACTIVE: You can interact with the iOS device by viewing, touching, and rotating the screen. You cannot run XCUITest framework-based tests in this mode.</p> </li> <li> <p>NO_VIDEO: You are connected to the device, but cannot interact with it or view the screen. This mode has the fastest test execution speed. You can run XCUITest framework-based tests in this mode.</p> </li> <li> <p>VIDEO_ONLY: You can view the screen, but cannot touch or rotate it. You can run XCUITest framework-based tests and watch the screen in this mode.</p> </li> </ul>"
        }
      ]
    },
    "skipAppResign": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SkipAppResign"
        },
        {
          "description": "<p>When set to <code>true</code>, for private devices, Device Farm does not sign your app again. For public devices, Device Farm always signs your apps again.</p> <p>For more information about how Device Farm re-signs your apps, see <a href=\"http://aws.amazon.com/device-farm/faqs/\">Do you modify my app?</a> in the <i>AWS Device Farm FAQs</i>.</p>"
        }
      ]
    },
    "vpcConfig": {
      "allOf": [
        {
          "$ref": "#/components/schemas/VpcConfig"
        },
        {
          "description": "The VPC security groups and subnets that are attached to a project."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-device-farm/examples/amazon-device-farm-remote-access-session-example.json
{
  "arn": "arn:aws:devicefarm:us-west-2:123456789012:project:abc123",
  "name": "Example name",
  "created": "example-created",
  "status": "COMPLETED",
  "result": "PASSED",
  "message": "An example message",
  "started": "example-started",
  "stopped": "example-stopped",
  "device": "example-device",
  "instanceArn": "arn:aws:devicefarm:us-west-2:123456789012:project:abc123",
  "remoteDebugEnabled": "example-remoteDebugEnab",
  "remoteRecordEnabled": "example-remoteRecordEna",
  "remoteRecordAppArn": "arn:aws:devicefarm:us-west-2:123456789012:project:abc123",
  "hostAddress": "example-hostAddress",
  "clientId": "example-clientId",
  "billingMethod": "example-billingMethod",
  "deviceMinutes": "example-deviceMinutes",
  "endpoint": "example-endpoint",
  "deviceUdid": "example-deviceUdid",
  "interactionMode": "example-interactionMode",
  "skipAppResign": "example-skipAppResign",
  "vpcConfig": "example-vpcConfig"
}
